### ISSUE TITLE
Please provide the form error

### ISSUE THREAD

**Issue by asiniy** [jessepollak/card#142]
Hey!

There is a trouble with this plugin. It seems very strange, but I really don't know what to do now.

``` coffee
$ -> # jQuery
  $('form.credit_card').card
    # a selector or DOM element for the container
    # where you want the card to appear
    container: ".card-wrapper" # *required*
    formSelectors:
      numberInput: "input#number" # optional — default input[name="number"]
      expiryInput: "input#expiry" # optional — default input[name="expiry"]
      cvcInput: "input#cvc" # optional — default input[name="cvc"]
      nameInput: "input#name" # optional - defaults input[name="name"]

    width: 200 # optional — default 350px
    formatting: true # optional - default true

    # Strings for translation - optional
    messages:
      validDate: "valid\ndate" # optional - default 'valid\nthru'
      monthYear: "mm/yyyy" # optional - default 'month/year'


    # Default values for rendered fields - optional
    values:
      number: "•••• •••• •••• ••••"
      name: "Full Name"
      expiry: "••/••"
      cvc: "•••"


    # if true, will log helpful messages for setting up Card
    debug: false # optional - default false
```

I'm using your plugin with coffeescript, and I'm getting `Please provide a form` error.
I've tryed to use `new Card({ form: 'bla-bla-bla', ... })` syntax, but without any happiness. What I'm doing wrong?

Alex

**Comment by Romanx** [comment]
Hello, I was trying to do use this also and found that the issue is related to [this line](https://github.com/jessepollak/card/blob/master/src/coffee/jquery.card.coffee#L19). the first argument is the form passed into the jquery selector and the second is the options however the actual function for creating a new Card only takes one argument (see [here](https://github.com/jessepollak/card/blob/master/src/coffee/card.coffee#L73)), the options which is why you get the complaint about the form.

Even after you get that working there's an issue with other code expecting JQuery selectors and not receiving them.

**Comment by ideiadeweb** [comment]
Same problem here =/

**Comment by jessepollak** [comment]
Sorry about this error! I'm shipping beta-2 in a bit which will fix this issue.
