### ISSUE TITLE
demo broken

### ISSUE THREAD

**Issue by talmroth** [jessepollak/card#156]
Not sure why I thought this had anything to do with CSS.  Its a script error.

[Error] TypeError: undefined is not a function (evaluating '$('.active form').card({ container: $('.card-wrapper')})')
	global code (card, line 145)

mac safari, chrome, pc chrome

**Comment by jessepollak** [comment]
All sorts of issues, thanks for the heads up :)

1. Wasn't using the new beta initialization style (still using the jQuery version). This should never have worked.
2. It worked for me because `cdn.rawgit` caches permanently the resource — so I was still being served a very old .js file.

Both issues fixed!
