### ISSUE TITLE
Card element is not de-focused on input blur

### ISSUE THREAD

**Issue by thenikso** [jessepollak/card#163]
I've spotted this (in the `card.js` file):

```
QJ.on(el, 'blur', function() {
      return QJ.removeClass(el, 'jp-card-focused');
});
```

I believe that the removeClass should be applied to `out` instead

**Comment by jessepollak** [comment]
Thank you for the bug report and triaging, I really appreciate it. This is definitely a bug and will be fixed.

This is a terrific candidate for a first time pull request from someone new to contributing or open source. In order to fix the issue, here's what needs to happen.

1. Fork then clone the repo and get development running on your computer. Instructions [here](https://github.com/jessepollak/card#development).
2. Replicate the issue. You should see that as you enter information, the `jp-card-focused` class does not get removed from the matching fields to inputs you previously were in.
3. Find the line of code in `card.coffee` that corresponds with the code snippet above.
4. Change the code to `removeClass` from `out` (the outputted display `<div>`) rather than `el` (the input where you are typing).
5. Verify that your fix works and that the `jp-card-focused` field is now being removed correctly.
6. Run `NODE_ENV=production gulp build` to build your changes in the production build
7. Commit your changes with an informative description
8. Open a pull request to this repo with your new commit and mention that you are fixing this issue.
9. I'll merge it in, then we'll digitally celebrate.

🎉🎊💫✨

Who wants to give it a go?
