### ISSUE TITLE
Handle Initial Values returning array

### ISSUE THREAD

**Issue by newtonrd** [jessepollak/card#166]
```javascript
+  Card.prototype.handleInitialValues = function() {
+    return $.each(this.options.formSelectors, (function(_this) {
+      return function(name, selector) {
+        var el;
+        el = _this["$" + name];
+        if (el.val()) {
+          console.log('hi');
+          el.trigger('paste');
+          return setTimeout(function() {
+            return el.trigger('keyup');
+          });
+        }
+      };
+    })(this));
+  };
```

When I run this code to initialize values, it seems that `_this["$" + name]` returns an array. This causes the el.val() to not work as expected. Why would I have an array in this instance?

**Comment by jessepollak** [comment]
Thank you for the report and triaging, much appreciated!

Looking at this more, I'm not quite sure what you're trying to do here. That logic is internal logic that handles the case where the `input` elements have values when the page loads, not something that should be used externally. 

I'm closing for now, if you'd like to share some more context, just reopen with more information and I'll take a look.

**Comment by fagnercarvalho** [comment]
Hello,

I think I got the very same problem. What he is trying to say is that because `_this["$" + name]` is returning a array the initial values aren't loaded into the card.

![array-selector](https://cloud.githubusercontent.com/assets/817867/12125871/fea2c196-b3d4-11e5-9650-54f39bc0445f.png)

![undefined-element](https://cloud.githubusercontent.com/assets/817867/12125835/c47b2f94-b3d4-11e5-8f19-06c42dd15397.png)

I'm not sure what is causing this exactly. What you think?

Regards,
Fagner

**Comment by jessepollak** [comment]
I'm still not sure what's going on here — is the `handleInitialValues` function something that you are adding? It doesn't seem to be in the card codebase.

In general, I'm looking for a solution that solves this issue, follow the progress in #184.
