### ISSUE TITLE
Card width option is not applied when form is not visible at initialization

### ISSUE THREAD

**Issue by mquan** [jessepollak/card#204]
I have my credit card form in a modal popup that isn't visible on load. If I have the card initialization happens on load, then when the form pops up, everything works fine except for the width option, which doesn't get applied.

The workaround I currently have is to initialize only on popup show. But it's a little ugly because I need to keep a variable for checking that card is already initialized on subsequent popups. It'd be nice if this could work out of the box.

**Comment by jessepollak** [comment]
This happens because we use the width of the container to dynamically scale the card. This will only happen if you are hiding the Card container with `display: none` (because then the container width is equal to 0). 

To fix this, use `visibility: hidden` instead of `display: none`.

Thanks for the report — please reopen if you are still having issues!

**Comment by mquan** [comment]
@jessepollak thanks, I'll try `visibility: hidden`
fyi @ngan

**Comment by lulalalalistia** [comment]
Sometimes `visibility: hidden` is not feasible. Could it be possible to have an option to skip the scaling?
