### ISSUE TITLE
Split CSS out into a separate repository

### ISSUE THREAD

**Issue by i--storm** [jessepollak/card#217]
How to compile css for project?

**Comment by jessepollak** [comment]
The CSS is automatically included in the JavaScript, so you don't need to include it manually. That said, I'm considering splitting out the CSS into a separate repo so it can be built by itself.

**Comment by barinali** [comment]
Hi @i--storm,

As far as @jessepollak says, compiled js file contains compiled css. So you don't have to include/import any file into your page. But, if you want to write some scss for this library, I think you need to do something about that. Like bourbon installing, and bourbon path updating.. Because when I wanted to build this library myself, I have to do this.

Firstly, you need to install bourbon your env with `gem install bourbon`. Then, you need to remove `src/scss/bourbon/` directory and install bourbon with `bourbon install` when you was in `src/scss/` directory. After this installation, you need to update bourbon import line with `@import "bourbon/bourbon";` in the card.scss.

Now, you can build this library with `gulp build` command on CLI.

I hope it works.

**Comment by BallisticPain** [comment]
Ah... put this into the documentation! #290 I thankfully found this so I don't have to build. TBH I didn't test to see if it would work without it... glad it will!

**Comment by fulldecent** [comment]
I recommend to close this issue as out-of-scope.

Documentation is updated and works well. Should be helping enough people with that.
