### ISSUE TITLE
Responsive Card Image

### ISSUE THREAD

**Issue by jemichael** [jessepollak/card#226]
Hi, how do I set this to be max of 350 but also have it stink in smaller viewports? Normally with an image, I add class img-responsive to the image class and bootstraps handles. Thanks!

**Comment by thomasrye** [comment]
The problem is that the card is not an image. It is a collection of elements and text styled to look like a credit card, but it's actually all html and css (which is pretty sweet in it's own way).

The solution to having it be responsive is probably not very straight forward (aka easy). You could define a js variable that gets the screen width before you run the card setup perhaps.

**Comment by jessepollak** [comment]
You can use the CSS `transform: scale(.5)` property to scale the card container for smaller screen sizes. Let me know if you have any issues with that!

**Comment by DuckSportsFan** [comment]
With a general white background layout, this worked for me for 320+px width devices...where close enough is okay...

`
@media only screen and (max-width: 480px){
   .card-wrapper {background-color:transparent !important}
   .jp-card, .jp-card.jp-card-back { transform: scale(.97,.958);position:relative;top: 7px !important;left: -12px !important }
   .jp-card.jp-card-flipped { height:94% !important;width:50% !important;position:relative;top: 12px !important;left: -12px !important}
}
`

**Comment by Moworks** [comment]
This worked for me:

 .jp-card-container { transform: scale(0.7,0.7); }
