### ISSUE TITLE
What level of PCI compliance do you need in order to use Card?

### ISSUE THREAD

**Issue by esetnik** [jessepollak/card#233]
I was wondering if someone could talk about and add to the README some information on PCI compliance rules for using this project.

My understanding is that this project can only be used if the vendor is scoped for SAQ D but i'm not sure. I'd love to use this project in conjunction with a solution like Braintree hosted fields to reduce PCI compliance burden but at this point I don't see how that's possible.

> For a merchant to be eligible for the easiest level of PCI compliance—SAQ A—payment fields cannot be hosted on your checkout page. All payment fields (credit card number, CVV, and expiration date) must be hosted on an external payment gateway's domain and presented to the user in a frame or with a redirect.

[Braintree Payments](https://developers.braintreepayments.com/guides/hosted-fields/overview/javascript/v2)

**Comment by h3smith** [comment]
I believe Braintree/Paypal is describing the issue incorrectly. The issue is where the data **_goes_**. If the data goes through your servers, they must be PCI Compliant. What they are claiming maybe true for how _their_ solution is architected.

If what Braintree proposes is true, anyone using Stripe wouldn't be in compliance. Which is simply not the case.

(_Note: I am not a PCI compliance specialist, if you have real concerns talk with your legal team_)

**Comment by esetnik** [comment]
@h3smith thanks for your reply. Unfortunately as I understand it the requirements are around who the data *touches* not solely where it *goes*. This includes the fact that your javascript may not have access to the sensitive card data (which means that you actually cannot do any custom client-side formatting of the inputs). The way providers like Braintree and Stripe work around these issues is by either hosting iFrames, hosted fields (one iFrame per input), or requiring increased PCI compliance scope.

I'm not aware of any Braintree or Stripe client tokenization procedure that doesn't require scope greater than SAQ A-EP.

**Comment by esetnik** [comment]
I also strongly doubt that Braintree would be explaining the issue incorrectly. They are in the business and should know this stuff better than any of us.

**Comment by jessepollak** [comment]
I'm not an expert on PCI compliance, so I'm not sure I have much to add here. I'll leave this open in case someone with more knowledge wants to chime in.

**Comment by mbuk** [comment]
To be compliant with stripe the magnetic card data should not hit your server and your payment page should be served via SSL/TLS.

Stripe handle this by not giving the form elements a name attribute and their form is passed to their server using an iframe.  They tokenise the card and insert the token back into your calling form.

eg:
`<input type="text" name="number" placeholder="Card number">` 
would not be valid because when stripe's callback fires your form will post number to your server

`<input type="text" placeholder="Card number">` 
is valid because it lacks the name attribute so you'll just get the token and any other fields with a name attribute.

[https://support.stripe.com/questions/do-i-need-to-be-pci-compliant-what-do-i-have-to-do](https://support.stripe.com/questions/do-i-need-to-be-pci-compliant-what-do-i-have-to-do)
[https://stripe.com/docs/security/ssl](https://stripe.com/docs/security/ssl)

**Comment by jessepollak** [comment]
Thank you for the clarification @mbuk!

**Comment by shayneoAtNorwood** [comment]
The nutshell as I understand it is, dont store the number (Including in the session! You'd be surprised how leaky even server side sessions are once a hacker gets inside your box) , ALWAYS use encryption, and if you need to retain access to the card, save the *token* not the details. This applies to ALL fields on the card, even the name (You can store a separately entered name, and pre-fill the card, but dont save whatrever they typed in). You may for convenience save a 4 digit excerpt of the number and I believe its OK to save the expiry date (So you can hassle the user to update their card when its ready to expire). Also, be secure, and keep up to date with all the security issues of your prefered platform (Never interpolate sql!!!!!!!!). The remaining PCI is mostly in relation to credit provider security ,and include things like datacenter security and the like. This probably wont affect you.
