### ISSUE TITLE
Is it possible to listen for card types.

### ISSUE THREAD

**Issue by Romanulus** [jessepollak/card#277]
Sorry if I am not catching this, if it exists, but would there be a way to listen for card types when a match is made?

**Comment by RupW** [comment]
Yes, there's an event payment.cardType that gets raised on the number input field whenever it changes. For example if you go to the demo page http://jessepollak.github.io/card/ then open a JavaScript console and run

    document.getElementsByName('number')[1].addEventListener('payment.cardType', function(event) {
        console.log(event.detail);
    })

then you'll get a log every time the card type changes of e.g. unknown, mastercard, visa. (Obviously that's hacked together for that one page and you should find a better way to select the one element, but I couldn't see one for that page at first glance.)

However because this is an event with a dot in the middle it clashes with jQuery's event namespacing - if you try to bind to 'payment.cardType' then jQuery thinks you mean an event 'payment' that you might later want to refer to as 'payment.cardType' e.g. to trigger just that one or remove just that one amongst any other 'payment' handlers on the same element. So there may be a trick you can use to bind to this using `$('input[name=number').on()`, but  the naive way

    $("input[name=number]").on('payment.cardType', function(event) { console.log(event.data); })

won't work.

**Comment by fulldecent** [comment]
Hello @Romanulus, would you please be able to update the documentation including this trick as a way to close this issue?
