### ISSUE TITLE
Please Add TROY

### ISSUE THREAD

**Issue by erenyavuz** [jessepollak/card#394]
TROY Turkey's new payment method
You can access the information from the link below.
https://troyodeme.com/en/

**Comment by RupW** [comment]
The first step is to get it added to the [payment](https://github.com/jessepollak/payment/) project, since that's the source of the card details array.

https://github.com/jessepollak/payment/blob/master/src/index.coffee#L5

You'll need the exact card number pattern to identify TROY and the CVV length. I don't see that information at your link. Can you raise a PR against payment with the details?

I'd guess you'll also need an initialisation flag to say when to recognise TROY numbers or not, as I'd guess not all payment processors will accept the cards.

**Comment by uslualper** [comment]
I made some additions, it works. 

**CSS**
```
.jp-card-logo.jp-card-troy {
    text-transform: lowercase;
    color: #fff;
    text-align: center;
    font-weight: 700;
    font-size: 24px;
    line-height: 18px;
    margin-top: 5px
}

.jp-card-logo.jp-card-troy:after,
.jp-card-logo.jp-card-troy:before {
    content: \"\";
    display: block;
    width: 26%;
    height: 6%;
    background: #22b8c3;
    right: 32%;
    top: 24%;
    position: absolute;
    transform: rotate(105deg);
}

.jp-card.jp-card-troy.jp-card-identified .jp-card-back:before,
.jp-card.jp-card-troy.jp-card-identified .jp-card-front:before {
    background-color: #01adba
}

.jp-card.jp-card-troy.jp-card-identified .jp-card-logo.jp-card-troy {
    opacity: 1;
    box-shadow: none
}
```

**Objects**
```
Card.prototype.cardTemplate = ... +  '<div class="jp-card-logo jp-card-troy">troy</div>' + ... ;

Card.prototype.cardTypes = [... , 'jp-card-elo','jp-card-troy'];

cards = [
...  ,
{
			type: 'troy',
			pattern: /^9792/,
			format: defaultFormat,
			length: [16],
			cvcLength: [3],
			luhn: true
		  }
]
```

**Comment by melloware** [comment]
I submitted Troy to payment.js with this PR: https://github.com/jessepollak/payment/pull/108

Also I added TROY to my rollup build of card which contains a lot of the fixes posted here. You can download it here: https://github.com/melloware/card/tree/master/dist

Screenshot:
![image](https://user-images.githubusercontent.com/4399574/80279799-c9c88200-86cd-11ea-93b1-edf40cc0c93d.png)

**Comment by melloware** [comment]
Added in 2.5.0

**Comment by mustafayusufozcan** [comment]
https://github.com/mustafayusufozcan/card

**Comment by melloware** [comment]
@mustafayusufozcan troy has already been added in 2.5.0?  Are you saying its not correct?  if so please submit a PR.
