### ISSUE TITLE
Problem with expiration date mask (MM / YY) on some cell phones in Chrome

### ISSUE THREAD

**Issue by FelipoAntonoff** [jessepollak/card#446]
Hello, I noticed that you are having problems with cell phones in the mask part of the expiration date of the Card, depending on the cell phone in Chrome you lose the MM / AA mask, I tested it on a Samsumg S7, but other devices also have a problem and some take it normally.

There was no error in the Console, just did not basically get the mask.
Interestingly the part of the Card number works normally.

Usage example:
```javascript
                 this.card = new Card({
                    form: '#code-mp-form',
                    container: '#card-wrapper',
                    formSelectors: {
                        numberInput: 'input#number',
                        expiryInput: 'input#expiry',
                        cvcInput: 'input#cvc',
                        nameInput: 'input#name'
                    },
                    messages: {
                        validDate: 'venc',
                        monthYear: 'mes/ano'
                    },
                    placeholders: {
                        number: '•••• •••• •••• ••••',
                        name: '{{ titular }}',
                        expiry: '••/••',
                        cvc: '•••'
                    },
                });
```

**Comment by utasar** [comment]
got same problem, i solved with **formatting = false** and masked with **RobinHerbots/jquery.inputmask**

here is example with jquery.inputmask in cvc input:
`placeholder="•••" data-inputmask="'mask': '999'"`

and input catch:
`jQuery(function ($) {
//shopform validate start
Inputmask({
showMaskOnHover: false,
showMaskOnFocus: false,
	
}).mask(document.querySelectorAll("input"));
//shopform validate end
});`

but for now credit card type detect not working because this plugin using **formatting** for detect credit card type.

**Comment by rafahernandez** [comment]
Also encountered this, found a related issue #199 don't think there was ever a PR, but I fixed with 

https://github.com/jessepollak/card/issues/199#issuecomment-183959467
> working on android devices with input type="tel" instead of input type="text"

**Comment by melloware** [comment]
Workaround provided for Android.
